name = "Puzzle"
defaultTargets = ["Puzzle"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = true
relaxedAutoImplicit = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "Puzzle"
